apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ediff-artifacts
  labels:
    app.kubernetes.io/name: ediff
    app.kubernetes.io/component: reproducibility
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
